/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Utils */

#ifndef _Included_Utils
#define _Included_Utils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Utils
 * Method:    printstuff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_oracle_truffle_vec_utils_Utils_nativePackMatrices
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jint, jint, jint, jint, jint, jint, jint, jint, jdoubleArray, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
